### ISSUE TITLE
Scrapping data from RKI excel failed

### ISSUE THREAD

**Issue by einstweilen** [ThisIsBenny/rki-vaccination-data#54]
Hi,

since today (Datenstand: 18.01.22, 08:00 Uhr) the RKI Excel document has new columns for 'Novavax' ('H' and 'N') on the 'Impfungen_Impfstoff' page, this breaks the parser and the API returns:

https://rki-vaccination-data.vercel.app/api and https://rki-vaccination-data.vercel.app/api/v2 

{
    "message": "scrapping data from RKI excel failed"
}

**Comment by burnziii** [comment]
Would be nice if this gets an update

**Comment by seiz** [comment]
Kann den Fehler auch bestätigen. Fix wäre klasse.

**Comment by burnziii** [comment]
Wäre es nicht auch besser anstatt ein Excel Dokument auseinander zu nehmen direkt die Werte aus der CSV zu nehmen?
https://github.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland/blob/4bcef2add8a9df79471f56a74693ed2485391987/Aktuell_Deutschland_Bundeslaender_COVID-19-Impfungen.csv

**Comment by sebastianruehmann** [comment]
Heads up! Still an issue. Would be great to know this fixed.
If there is anything you could need support with, feel free to reach out.

**Comment by ThisIsBenny** [comment]
issue is fixed.

@burnziii the csv wasn't available as i have started the project. The RKI provided the data the first time as csv at july 2021

**Comment by burnziii** [comment]
still getting error when try to reach https://rki-vaccination-data.vercel.app/api

**Comment by ThisIsBenny** [comment]
@burnziii it would be better to switch to the v2 api. the v1 api is marked as deprecated from my side.
i will fix it for now, but i can't guarantee that the v1 version will work in the future.
fix => https://github.com/ThisIsBenny/rki-vaccination-data/pull/56
